# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackathon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.0.0'
  pod 'Parse'
  pod 'Parse/UI'
  pod 'BRYXBanner'
  pod 'SCLAlertView'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire'

  # Pods for hackathon

end
